// @generated by scripts/build-registry-index.ts
"use client";
import dynamic from "next/dynamic";
import type { ComponentType } from "react";

function LoadingPreview() {
  return <output>Loading preview…</output>;
}
export const BlockLoaders: Record<string, ComponentType> = {
  "ai-chat": dynamic(() => import("@/registry/brook/blocks/ai-chat/page"), { ssr: false, loading: LoadingPreview }),
  "ai-chat-tailwind": dynamic(() => import("@/registry/brook/tailwind/blocks/ai-chat/page"), {
    ssr: false,
    loading: LoadingPreview,
  }),
  "card-image-section": dynamic(() => import("@/registry/brook/blocks/card-image-section/page")),
  "card-image-section-tailwind": dynamic(() => import("@/registry/brook/tailwind/blocks/card-image-section/page")),
  "card-login": dynamic(() => import("@/registry/brook/blocks/card-login/page"), {
    ssr: false,
    loading: LoadingPreview,
  }),
  "card-login-tailwind": dynamic(() => import("@/registry/brook/tailwind/blocks/card-login/page"), {
    ssr: false,
    loading: LoadingPreview,
  }),
  "card-progress": dynamic(() => import("@/registry/brook/blocks/card-progress/page")),
  "card-progress-tailwind": dynamic(() => import("@/registry/brook/tailwind/blocks/card-progress/page")),
  "card-task": dynamic(() => import("@/registry/brook/blocks/card-task/page"), { ssr: false, loading: LoadingPreview }),
  "card-task-tailwind": dynamic(() => import("@/registry/brook/tailwind/blocks/card-task/page"), {
    ssr: false,
    loading: LoadingPreview,
  }),
  "card-traffic": dynamic(() => import("@/registry/brook/blocks/card-traffic/page"), {
    ssr: false,
    loading: LoadingPreview,
  }),
  "card-traffic-tailwind": dynamic(() => import("@/registry/brook/tailwind/blocks/card-traffic/page"), {
    ssr: false,
    loading: LoadingPreview,
  }),
  "expandable-card-carousel": dynamic(() => import("@/registry/brook/blocks/expandable-card-carousel/page"), {
    ssr: false,
    loading: LoadingPreview,
  }),
  "expandable-card-carousel-tailwind": dynamic(
    () => import("@/registry/brook/tailwind/blocks/expandable-card-carousel/page"),
    { ssr: false, loading: LoadingPreview }
  ),
  "expandable-card-spread": dynamic(() => import("@/registry/brook/blocks/expandable-card-spread/page"), {
    ssr: false,
    loading: LoadingPreview,
  }),
  "expandable-card-spread-tailwind": dynamic(
    () => import("@/registry/brook/tailwind/blocks/expandable-card-spread/page"),
    { ssr: false, loading: LoadingPreview }
  ),
  "pricing-section": dynamic(() => import("@/registry/brook/blocks/pricing-section/page")),
  "pricing-section-tailwind": dynamic(() => import("@/registry/brook/tailwind/blocks/pricing-section/page")),
};
