// @generated
// This file is autogenerated by scripts/build-registry-index.ts
// Do not edit this file directly.
// @ts-nocheck

type RegistryEntry = {
  name: string;
  type: "example" | "block" | "ui";
  files?: string[];
  path?: string;
};

export const Index: Record<string, RegistryEntry> = {
  "accordion-demo": {
    name: "accordion-demo",
    type: "example",
    files: ["registry/brook/examples/accordion-demo/accordion-demo.tsx"],
    path: "@/registry/brook/examples/accordion-demo/accordion-demo",
  },
  "accordion-minimal": {
    name: "accordion-minimal",
    type: "example",
    files: [
      "registry/brook/examples/accordion-minimal/accordion-minimal.tsx",
      "registry/brook/examples/accordion-minimal/accordion-minimal.module.css",
    ],
    path: "@/registry/brook/examples/accordion-minimal/accordion-minimal",
  },
  "alert-demo": {
    name: "alert-demo",
    type: "example",
    files: [
      "registry/brook/examples/alert-demo/alert-demo.tsx",
      "registry/brook/examples/alert-demo/alert-demo.module.css",
    ],
    path: "@/registry/brook/examples/alert-demo/alert-demo",
  },
  "alert-destructive": {
    name: "alert-destructive",
    type: "example",
    files: [
      "registry/brook/examples/alert-destructive/alert-destructive.tsx",
      "registry/brook/examples/alert-destructive/alert-destructive.module.css",
    ],
    path: "@/registry/brook/examples/alert-destructive/alert-destructive",
  },
  "alert-dialog-demo": {
    name: "alert-dialog-demo",
    type: "example",
    files: [
      "registry/brook/examples/alert-dialog-demo/alert-dialog-demo.tsx",
      "registry/brook/examples/alert-dialog-demo/alert-dialog-demo.module.css",
    ],
    path: "@/registry/brook/examples/alert-dialog-demo/alert-dialog-demo",
  },
  "alert-dialog-nested": {
    name: "alert-dialog-nested",
    type: "example",
    files: [
      "registry/brook/examples/alert-dialog-nested/alert-dialog-nested.tsx",
      "registry/brook/examples/alert-dialog-nested/alert-dialog-nested.module.css",
    ],
    path: "@/registry/brook/examples/alert-dialog-nested/alert-dialog-nested",
  },
  "alert-info": {
    name: "alert-info",
    type: "example",
    files: [
      "registry/brook/examples/alert-info/alert-info.tsx",
      "registry/brook/examples/alert-info/alert-info.module.css",
    ],
    path: "@/registry/brook/examples/alert-info/alert-info",
  },
  "alert-success": {
    name: "alert-success",
    type: "example",
    files: [
      "registry/brook/examples/alert-success/alert-success.tsx",
      "registry/brook/examples/alert-success/alert-success.module.css",
    ],
    path: "@/registry/brook/examples/alert-success/alert-success",
  },
  "alert-warning": {
    name: "alert-warning",
    type: "example",
    files: [
      "registry/brook/examples/alert-warning/alert-warning.tsx",
      "registry/brook/examples/alert-warning/alert-warning.module.css",
    ],
    path: "@/registry/brook/examples/alert-warning/alert-warning",
  },
  "autocomplete-auto-highlight": {
    name: "autocomplete-auto-highlight",
    type: "example",
    files: [
      "registry/brook/examples/autocomplete-auto-highlight/autocomplete-auto-highlight.tsx",
      "registry/brook/examples/autocomplete-auto-highlight/autocomplete-auto-highlight.module.css",
    ],
    path: "@/registry/brook/examples/autocomplete-auto-highlight/autocomplete-auto-highlight",
  },
  "autocomplete-clearable": {
    name: "autocomplete-clearable",
    type: "example",
    files: [
      "registry/brook/examples/autocomplete-clearable/autocomplete-clearable.tsx",
      "registry/brook/examples/autocomplete-clearable/autocomplete-clearable.module.css",
    ],
    path: "@/registry/brook/examples/autocomplete-clearable/autocomplete-clearable",
  },
  "autocomplete-demo": {
    name: "autocomplete-demo",
    type: "example",
    files: [
      "registry/brook/examples/autocomplete-demo/autocomplete-demo.tsx",
      "registry/brook/examples/autocomplete-demo/autocomplete-demo.module.css",
    ],
    path: "@/registry/brook/examples/autocomplete-demo/autocomplete-demo",
  },
  "autocomplete-fuzzy": {
    name: "autocomplete-fuzzy",
    type: "example",
    files: [
      "registry/brook/examples/autocomplete-fuzzy/autocomplete-fuzzy.tsx",
      "registry/brook/examples/autocomplete-fuzzy/autocomplete-fuzzy.module.css",
    ],
    path: "@/registry/brook/examples/autocomplete-fuzzy/autocomplete-fuzzy",
  },
  "autocomplete-grouped": {
    name: "autocomplete-grouped",
    type: "example",
    files: [
      "registry/brook/examples/autocomplete-grouped/autocomplete-grouped.tsx",
      "registry/brook/examples/autocomplete-grouped/autocomplete-grouped.module.css",
    ],
    path: "@/registry/brook/examples/autocomplete-grouped/autocomplete-grouped",
  },
  "avatar-demo": {
    name: "avatar-demo",
    type: "example",
    files: ["registry/brook/examples/avatar-demo.tsx"],
    path: "@/registry/brook/examples/avatar-demo",
  },
  "avatar-group": {
    name: "avatar-group",
    type: "example",
    files: [
      "registry/brook/examples/avatar-group/avatar-group.tsx",
      "registry/brook/examples/avatar-group/avatar-group.module.css",
    ],
    path: "@/registry/brook/examples/avatar-group/avatar-group",
  },
  "avatar-motion": {
    name: "avatar-motion",
    type: "example",
    files: ["registry/brook/examples/avatar-motion/avatar-motion.tsx"],
    path: "@/registry/brook/examples/avatar-motion/avatar-motion",
  },
  "background-demo": {
    name: "background-demo",
    type: "example",
    files: [
      "registry/brook/examples/background-demo/background-demo.tsx",
      "registry/brook/examples/background-demo/background-demo.module.css",
    ],
    path: "@/registry/brook/examples/background-demo/background-demo",
  },
  "badge-demo": {
    name: "badge-demo",
    type: "example",
    files: [
      "registry/brook/examples/badge-demo/badge-demo.tsx",
      "registry/brook/examples/badge-demo/badge-demo.module.css",
    ],
    path: "@/registry/brook/examples/badge-demo/badge-demo",
  },
  "badge-error": {
    name: "badge-error",
    type: "example",
    files: [
      "registry/brook/examples/badge-error/badge-error.tsx",
      "registry/brook/examples/badge-error/badge-error.module.css",
    ],
    path: "@/registry/brook/examples/badge-error/badge-error",
  },
  "badge-external-links": {
    name: "badge-external-links",
    type: "example",
    files: [
      "registry/brook/examples/badge-external-links/badge-external-links.tsx",
      "registry/brook/examples/badge-external-links/badge-external-links.module.css",
    ],
    path: "@/registry/brook/examples/badge-external-links/badge-external-links",
  },
  "badge-sizes": {
    name: "badge-sizes",
    type: "example",
    files: [
      "registry/brook/examples/badge-sizes/badge-sizes.tsx",
      "registry/brook/examples/badge-sizes/badge-sizes.module.css",
    ],
    path: "@/registry/brook/examples/badge-sizes/badge-sizes",
  },
  "badge-success": {
    name: "badge-success",
    type: "example",
    files: [
      "registry/brook/examples/badge-success/badge-success.tsx",
      "registry/brook/examples/badge-success/badge-success.module.css",
    ],
    path: "@/registry/brook/examples/badge-success/badge-success",
  },
  "button-demo": {
    name: "button-demo",
    type: "example",
    files: ["registry/brook/examples/button-demo.tsx"],
    path: "@/registry/brook/examples/button-demo",
  },
  "button-destructive": {
    name: "button-destructive",
    type: "example",
    files: ["registry/brook/examples/button-destructive.tsx"],
    path: "@/registry/brook/examples/button-destructive",
  },
  "button-disabled": {
    name: "button-disabled",
    type: "example",
    files: ["registry/brook/examples/button-disabled.tsx"],
    path: "@/registry/brook/examples/button-disabled",
  },
  "button-external-link": {
    name: "button-external-link",
    type: "example",
    files: ["registry/brook/examples/button-external-link.tsx"],
    path: "@/registry/brook/examples/button-external-link",
  },
  "button-ghost": {
    name: "button-ghost",
    type: "example",
    files: ["registry/brook/examples/button-ghost.tsx"],
    path: "@/registry/brook/examples/button-ghost",
  },
  "button-icon": {
    name: "button-icon",
    type: "example",
    files: ["registry/brook/examples/button-icon.tsx"],
    path: "@/registry/brook/examples/button-icon",
  },
  "button-loading": {
    name: "button-loading",
    type: "example",
    files: [
      "registry/brook/examples/button-loading/button-loading.tsx",
      "registry/brook/examples/button-loading/button-loading.module.css",
    ],
    path: "@/registry/brook/examples/button-loading/button-loading",
  },
  "button-outline": {
    name: "button-outline",
    type: "example",
    files: ["registry/brook/examples/button-outline.tsx"],
    path: "@/registry/brook/examples/button-outline",
  },
  "button-secondary": {
    name: "button-secondary",
    type: "example",
    files: ["registry/brook/examples/button-secondary.tsx"],
    path: "@/registry/brook/examples/button-secondary",
  },
  "button-sizes": {
    name: "button-sizes",
    type: "example",
    files: [
      "registry/brook/examples/button-sizes/button-sizes.tsx",
      "registry/brook/examples/button-sizes/button-sizes.module.css",
    ],
    path: "@/registry/brook/examples/button-sizes/button-sizes",
  },
  "button-with-arrow": {
    name: "button-with-arrow",
    type: "example",
    files: ["registry/brook/examples/button-with-arrow.tsx"],
    path: "@/registry/brook/examples/button-with-arrow",
  },
  "card-demo": {
    name: "card-demo",
    type: "example",
    files: [
      "registry/brook/examples/card-demo/card-demo.tsx",
      "registry/brook/examples/card-demo/card-demo.module.css",
    ],
    path: "@/registry/brook/examples/card-demo/card-demo",
  },
  "card-image-demo": {
    name: "card-image-demo",
    type: "example",
    files: [
      "registry/brook/examples/card-image-demo/card-image-demo.tsx",
      "registry/brook/examples/card-image-demo/card-image-demo.module.css",
    ],
    path: "@/registry/brook/examples/card-image-demo/card-image-demo",
  },
  "card-pricing-card": {
    name: "card-pricing-card",
    type: "example",
    files: [
      "registry/brook/examples/card-pricing-card/card-pricing-card.tsx",
      "registry/brook/examples/card-pricing-card/card-pricing-card.module.css",
    ],
    path: "@/registry/brook/examples/card-pricing-card/card-pricing-card",
  },
  "card-settings": {
    name: "card-settings",
    type: "example",
    files: ["registry/brook/examples/card-settings/card-settings.tsx"],
    path: "@/registry/brook/examples/card-settings/card-settings",
  },
  "card-transaction": {
    name: "card-transaction",
    type: "example",
    files: [
      "registry/brook/examples/card-transaction/card-transaction.tsx",
      "registry/brook/examples/card-transaction/card-transaction.module.css",
    ],
    path: "@/registry/brook/examples/card-transaction/card-transaction",
  },
  "carousel-demo": {
    name: "carousel-demo",
    type: "example",
    files: [
      "registry/brook/examples/carousel-demo/carousel-demo.tsx",
      "registry/brook/examples/carousel-demo/carousel-demo.module.css",
    ],
    path: "@/registry/brook/examples/carousel-demo/carousel-demo",
  },
  "chart-area-demo": {
    name: "chart-area-demo",
    type: "example",
    files: [
      "registry/brook/examples/chart-area-demo/chart-area-demo.tsx",
      "registry/brook/examples/chart-area-demo/chart-area-demo.module.css",
    ],
    path: "@/registry/brook/examples/chart-area-demo/chart-area-demo",
  },
  "chart-bar-demo": {
    name: "chart-bar-demo",
    type: "example",
    files: [
      "registry/brook/examples/chart-bar-demo/chart-bar-demo.tsx",
      "registry/brook/examples/chart-bar-demo/chart-bar-demo.module.css",
    ],
    path: "@/registry/brook/examples/chart-bar-demo/chart-bar-demo",
  },
  "chart-line-demo": {
    name: "chart-line-demo",
    type: "example",
    files: [
      "registry/brook/examples/chart-line-demo/chart-line-demo.tsx",
      "registry/brook/examples/chart-line-demo/chart-line-demo.module.css",
    ],
    path: "@/registry/brook/examples/chart-line-demo/chart-line-demo",
  },
  "chart-pie-demo": {
    name: "chart-pie-demo",
    type: "example",
    files: [
      "registry/brook/examples/chart-pie-demo/chart-pie-demo.tsx",
      "registry/brook/examples/chart-pie-demo/chart-pie-demo.module.css",
    ],
    path: "@/registry/brook/examples/chart-pie-demo/chart-pie-demo",
  },
  "checkbox-card": {
    name: "checkbox-card",
    type: "example",
    files: [
      "registry/brook/examples/checkbox-card/checkbox-card.tsx",
      "registry/brook/examples/checkbox-card/checkbox-card.module.css",
    ],
    path: "@/registry/brook/examples/checkbox-card/checkbox-card",
  },
  "checkbox-demo": {
    name: "checkbox-demo",
    type: "example",
    files: [
      "registry/brook/examples/checkbox-demo/checkbox-demo.tsx",
      "registry/brook/examples/checkbox-demo/checkbox-demo.module.css",
    ],
    path: "@/registry/brook/examples/checkbox-demo/checkbox-demo",
  },
  "checkbox-description": {
    name: "checkbox-description",
    type: "example",
    files: [
      "registry/brook/examples/checkbox-description/checkbox-description.tsx",
      "registry/brook/examples/checkbox-description/checkbox-description.module.css",
    ],
    path: "@/registry/brook/examples/checkbox-description/checkbox-description",
  },
  "checkbox-group-demo": {
    name: "checkbox-group-demo",
    type: "example",
    files: [
      "registry/brook/examples/checkbox-group-demo/checkbox-group-demo.tsx",
      "registry/brook/examples/checkbox-group-demo/checkbox-group-demo.module.css",
    ],
    path: "@/registry/brook/examples/checkbox-group-demo/checkbox-group-demo",
  },
  "checkbox-group-parent": {
    name: "checkbox-group-parent",
    type: "example",
    files: [
      "registry/brook/examples/checkbox-group-parent/checkbox-group-parent.tsx",
      "registry/brook/examples/checkbox-group-parent/checkbox-group-parent.module.css",
    ],
    path: "@/registry/brook/examples/checkbox-group-parent/checkbox-group-parent",
  },
  "collapsible-demo": {
    name: "collapsible-demo",
    type: "example",
    files: [
      "registry/brook/examples/collapsible-demo/collapsible-demo.tsx",
      "registry/brook/examples/collapsible-demo/collapsible-demo.module.css",
    ],
    path: "@/registry/brook/examples/collapsible-demo/collapsible-demo",
  },
  "combobox-auto-highlight": {
    name: "combobox-auto-highlight",
    type: "example",
    files: [
      "registry/brook/examples/combobox-auto-highlight/combobox-auto-highlight.tsx",
      "registry/brook/examples/combobox-auto-highlight/combobox-auto-highlight.module.css",
    ],
    path: "@/registry/brook/examples/combobox-auto-highlight/combobox-auto-highlight",
  },
  "combobox-clearable": {
    name: "combobox-clearable",
    type: "example",
    files: [
      "registry/brook/examples/combobox-clearable/combobox-clearable.tsx",
      "registry/brook/examples/combobox-clearable/combobox-clearable.module.css",
    ],
    path: "@/registry/brook/examples/combobox-clearable/combobox-clearable",
  },
  "combobox-demo": {
    name: "combobox-demo",
    type: "example",
    files: [
      "registry/brook/examples/combobox-demo/combobox-demo.tsx",
      "registry/brook/examples/combobox-demo/combobox-demo.module.css",
    ],
    path: "@/registry/brook/examples/combobox-demo/combobox-demo",
  },
  "combobox-grouped": {
    name: "combobox-grouped",
    type: "example",
    files: [
      "registry/brook/examples/combobox-grouped/combobox-grouped.tsx",
      "registry/brook/examples/combobox-grouped/combobox-grouped.module.css",
    ],
    path: "@/registry/brook/examples/combobox-grouped/combobox-grouped",
  },
  "combobox-multiple": {
    name: "combobox-multiple",
    type: "example",
    files: [
      "registry/brook/examples/combobox-multiple/combobox-multiple.tsx",
      "registry/brook/examples/combobox-multiple/combobox-multiple.module.css",
    ],
    path: "@/registry/brook/examples/combobox-multiple/combobox-multiple",
  },
  "command-demo": {
    name: "command-demo",
    type: "example",
    files: [
      "registry/brook/examples/command-demo/command-demo.tsx",
      "registry/brook/examples/command-demo/command-demo.module.css",
    ],
    path: "@/registry/brook/examples/command-demo/command-demo",
  },
  "context-menu-demo": {
    name: "context-menu-demo",
    type: "example",
    files: [
      "registry/brook/examples/context-menu-demo/context-menu-demo.tsx",
      "registry/brook/examples/context-menu-demo/context-menu-demo.module.css",
    ],
    path: "@/registry/brook/examples/context-menu-demo/context-menu-demo",
  },
  "copy-button-demo": {
    name: "copy-button-demo",
    type: "example",
    files: [
      "registry/brook/examples/copy-button-demo/copy-button-demo.tsx",
      "registry/brook/examples/copy-button-demo/copy-button-demo.module.css",
    ],
    path: "@/registry/brook/examples/copy-button-demo/copy-button-demo",
  },
  "dialog-demo": {
    name: "dialog-demo",
    type: "example",
    files: [
      "registry/brook/examples/dialog-demo/dialog-demo.tsx",
      "registry/brook/examples/dialog-demo/dialog-demo.module.css",
    ],
    path: "@/registry/brook/examples/dialog-demo/dialog-demo",
  },
  "dialog-motion": {
    name: "dialog-motion",
    type: "example",
    files: [
      "registry/brook/examples/dialog-motion/dialog-motion.tsx",
      "registry/brook/examples/dialog-motion/dialog-motion.module.css",
    ],
    path: "@/registry/brook/examples/dialog-motion/dialog-motion",
  },
  "dialog-sheet": {
    name: "dialog-sheet",
    type: "example",
    files: [
      "registry/brook/examples/dialog-sheet/dialog-sheet.tsx",
      "registry/brook/examples/dialog-sheet/dialog-sheet.module.css",
    ],
    path: "@/registry/brook/examples/dialog-sheet/dialog-sheet",
  },
  "dropdown-menu-demo": {
    name: "dropdown-menu-demo",
    type: "example",
    files: ["registry/brook/examples/dropdown-menu-demo/dropdown-menu-demo.tsx"],
    path: "@/registry/brook/examples/dropdown-menu-demo/dropdown-menu-demo",
  },
  "dropdown-menu-motion": {
    name: "dropdown-menu-motion",
    type: "example",
    files: [
      "registry/brook/examples/dropdown-menu-motion/dropdown-menu-motion.tsx",
      "registry/brook/examples/dropdown-menu-motion/dropdown-menu-motion.module.css",
    ],
    path: "@/registry/brook/examples/dropdown-menu-motion/dropdown-menu-motion",
  },
  "dropdown-menu-profile": {
    name: "dropdown-menu-profile",
    type: "example",
    files: [
      "registry/brook/examples/dropdown-menu-profile/dropdown-menu-profile.tsx",
      "registry/brook/examples/dropdown-menu-profile/dropdown-menu-profile.module.css",
    ],
    path: "@/registry/brook/examples/dropdown-menu-profile/dropdown-menu-profile",
  },
  "dropdown-menu-submenu": {
    name: "dropdown-menu-submenu",
    type: "example",
    files: [
      "registry/brook/examples/dropdown-menu-submenu/dropdown-menu-submenu.tsx",
      "registry/brook/examples/dropdown-menu-submenu/dropdown-menu-submenu.module.css",
    ],
    path: "@/registry/brook/examples/dropdown-menu-submenu/dropdown-menu-submenu",
  },
  "expandable-card-demo": {
    name: "expandable-card-demo",
    type: "example",
    files: [
      "registry/brook/examples/expandable-card-demo/expandable-card-demo.tsx",
      "registry/brook/examples/expandable-card-demo/expandable-card-demo.module.css",
    ],
    path: "@/registry/brook/examples/expandable-card-demo/expandable-card-demo",
  },
  "field-demo": {
    name: "field-demo",
    type: "example",
    files: [
      "registry/brook/examples/field-demo/field-demo.tsx",
      "registry/brook/examples/field-demo/field-demo.module.css",
    ],
    path: "@/registry/brook/examples/field-demo/field-demo",
  },
  "fieldset-demo": {
    name: "fieldset-demo",
    type: "example",
    files: [
      "registry/brook/examples/fieldset-demo/fieldset-demo.tsx",
      "registry/brook/examples/fieldset-demo/fieldset-demo.module.css",
    ],
    path: "@/registry/brook/examples/fieldset-demo/fieldset-demo",
  },
  "form-demo": {
    name: "form-demo",
    type: "example",
    files: ["registry/brook/examples/form-demo.tsx"],
    path: "@/registry/brook/examples/form-demo",
  },
  "input-demo": {
    name: "input-demo",
    type: "example",
    files: [
      "registry/brook/examples/input-demo/input-demo.tsx",
      "registry/brook/examples/input-demo/input-demo.module.css",
    ],
    path: "@/registry/brook/examples/input-demo/input-demo",
  },
  "like-button-demo": {
    name: "like-button-demo",
    type: "example",
    files: ["registry/brook/examples/like-button-demo.tsx"],
    path: "@/registry/brook/examples/like-button-demo",
  },
  "menubar-demo": {
    name: "menubar-demo",
    type: "example",
    files: [
      "registry/brook/examples/menubar-demo/menubar-demo.tsx",
      "registry/brook/examples/menubar-demo/menubar-demo.module.css",
    ],
    path: "@/registry/brook/examples/menubar-demo/menubar-demo",
  },
  "meter-demo": {
    name: "meter-demo",
    type: "example",
    files: [
      "registry/brook/examples/meter-demo/meter-demo.tsx",
      "registry/brook/examples/meter-demo/meter-demo.module.css",
    ],
    path: "@/registry/brook/examples/meter-demo/meter-demo",
  },
  "navigation-menu-demo": {
    name: "navigation-menu-demo",
    type: "example",
    files: [
      "registry/brook/examples/navigation-menu-demo/navigation-menu-demo.tsx",
      "registry/brook/examples/navigation-menu-demo/navigation-menu-demo.module.css",
    ],
    path: "@/registry/brook/examples/navigation-menu-demo/navigation-menu-demo",
  },
  "navigation-sub-menu": {
    name: "navigation-sub-menu",
    type: "example",
    files: [
      "registry/brook/examples/navigation-sub-menu/navigation-sub-menu.tsx",
      "registry/brook/examples/navigation-sub-menu/navigation-sub-menu.module.css",
    ],
    path: "@/registry/brook/examples/navigation-sub-menu/navigation-sub-menu",
  },
  "number-field-demo": {
    name: "number-field-demo",
    type: "example",
    files: [
      "registry/brook/examples/number-field-demo/number-field-demo.tsx",
      "registry/brook/examples/number-field-demo/number-field-demo.module.css",
    ],
    path: "@/registry/brook/examples/number-field-demo/number-field-demo",
  },
  "popover-animated": {
    name: "popover-animated",
    type: "example",
    files: [
      "registry/brook/examples/popover-animated/popover-animated.tsx",
      "registry/brook/examples/popover-animated/popover-animated.module.css",
    ],
    path: "@/registry/brook/examples/popover-animated/popover-animated",
  },
  "popover-demo": {
    name: "popover-demo",
    type: "example",
    files: [
      "registry/brook/examples/popover-demo/popover-demo.tsx",
      "registry/brook/examples/popover-demo/popover-demo.module.css",
    ],
    path: "@/registry/brook/examples/popover-demo/popover-demo",
  },
  "preview-card-demo": {
    name: "preview-card-demo",
    type: "example",
    files: [
      "registry/brook/examples/preview-card-demo/preview-card-demo.tsx",
      "registry/brook/examples/preview-card-demo/preview-card-demo.module.css",
    ],
    path: "@/registry/brook/examples/preview-card-demo/preview-card-demo",
  },
  "progress-demo": {
    name: "progress-demo",
    type: "example",
    files: [
      "registry/brook/examples/progress-demo/progress-demo.tsx",
      "registry/brook/examples/progress-demo/progress-demo.module.css",
    ],
    path: "@/registry/brook/examples/progress-demo/progress-demo",
  },
  "radio-demo": {
    name: "radio-demo",
    type: "example",
    files: [
      "registry/brook/examples/radio-demo/radio-demo.tsx",
      "registry/brook/examples/radio-demo/radio-demo.module.css",
    ],
    path: "@/registry/brook/examples/radio-demo/radio-demo",
  },
  "scroll-area-demo": {
    name: "scroll-area-demo",
    type: "example",
    files: [
      "registry/brook/examples/scroll-area-demo/scroll-area-demo.tsx",
      "registry/brook/examples/scroll-area-demo/scroll-area-demo.module.css",
    ],
    path: "@/registry/brook/examples/scroll-area-demo/scroll-area-demo",
  },
  "select-demo": {
    name: "select-demo",
    type: "example",
    files: [
      "registry/brook/examples/select-demo/select-demo.tsx",
      "registry/brook/examples/select-demo/select-demo.module.css",
    ],
    path: "@/registry/brook/examples/select-demo/select-demo",
  },
  "separator-demo": {
    name: "separator-demo",
    type: "example",
    files: ["registry/brook/examples/separator-demo.tsx"],
    path: "@/registry/brook/examples/separator-demo",
  },
  shipping: {
    name: "shipping",
    type: "example",
    files: ["registry/brook/examples/shipping/shipping.tsx", "registry/brook/examples/shipping/shipping.module.css"],
    path: "@/registry/brook/examples/shipping/shipping",
  },
  "slider-demo": {
    name: "slider-demo",
    type: "example",
    files: [
      "registry/brook/examples/slider-demo/slider-demo.tsx",
      "registry/brook/examples/slider-demo/slider-demo.module.css",
    ],
    path: "@/registry/brook/examples/slider-demo/slider-demo",
  },
  "switch-demo": {
    name: "switch-demo",
    type: "example",
    files: [
      "registry/brook/examples/switch-demo/switch-demo.tsx",
      "registry/brook/examples/switch-demo/switch-demo.module.css",
    ],
    path: "@/registry/brook/examples/switch-demo/switch-demo",
  },
  "switch-with-label": {
    name: "switch-with-label",
    type: "example",
    files: [
      "registry/brook/examples/switch-with-label/switch-with-label.tsx",
      "registry/brook/examples/switch-with-label/switch-with-label.module.css",
    ],
    path: "@/registry/brook/examples/switch-with-label/switch-with-label",
  },
  "table-demo": {
    name: "table-demo",
    type: "example",
    files: ["registry/brook/examples/table-demo.tsx"],
    path: "@/registry/brook/examples/table-demo",
  },
  "tabs-demo": {
    name: "tabs-demo",
    type: "example",
    files: [
      "registry/brook/examples/tabs-demo/tabs-demo.tsx",
      "registry/brook/examples/tabs-demo/tabs-demo.module.css",
    ],
    path: "@/registry/brook/examples/tabs-demo/tabs-demo",
  },
  "tabs-motion": {
    name: "tabs-motion",
    type: "example",
    files: [
      "registry/brook/examples/tabs-motion/tabs-motion.tsx",
      "registry/brook/examples/tabs-motion/tabs-motion.module.css",
    ],
    path: "@/registry/brook/examples/tabs-motion/tabs-motion",
  },
  "tabs-vertical": {
    name: "tabs-vertical",
    type: "example",
    files: ["registry/brook/examples/tabs-vertical.tsx"],
    path: "@/registry/brook/examples/tabs-vertical",
  },
  "toast-demo": {
    name: "toast-demo",
    type: "example",
    files: ["registry/brook/examples/toast-demo.tsx"],
    path: "@/registry/brook/examples/toast-demo",
  },
  "toggle-demo": {
    name: "toggle-demo",
    type: "example",
    files: [
      "registry/brook/examples/toggle-demo/toggle-demo.tsx",
      "registry/brook/examples/toggle-demo/toggle-demo.module.css",
    ],
    path: "@/registry/brook/examples/toggle-demo/toggle-demo",
  },
  "toggle-group-demo": {
    name: "toggle-group-demo",
    type: "example",
    files: [
      "registry/brook/examples/toggle-group-demo/toggle-group-demo.tsx",
      "registry/brook/examples/toggle-group-demo/toggle-group-demo.module.css",
    ],
    path: "@/registry/brook/examples/toggle-group-demo/toggle-group-demo",
  },
  "toolbar-demo": {
    name: "toolbar-demo",
    type: "example",
    files: [
      "registry/brook/examples/toolbar-demo/toolbar-demo.tsx",
      "registry/brook/examples/toolbar-demo/toolbar-demo.module.css",
    ],
    path: "@/registry/brook/examples/toolbar-demo/toolbar-demo",
  },
  "tooltip-demo": {
    name: "tooltip-demo",
    type: "example",
    files: ["registry/brook/examples/tooltip-demo.tsx"],
    path: "@/registry/brook/examples/tooltip-demo",
  },
  "ai-chat": {
    name: "ai-chat",
    type: "block",
    files: [
      "registry/brook/blocks/ai-chat/page.tsx",
      "registry/brook/blocks/ai-chat/components/ai-chat.tsx",
      "registry/brook/blocks/ai-chat/components/ai-chat.module.css",
    ],
    path: "@/registry/brook/blocks/ai-chat/page",
  },
  "card-image-section": {
    name: "card-image-section",
    type: "block",
    files: [
      "registry/brook/blocks/card-image-section/page.tsx",
      "registry/brook/blocks/card-image-section/components/card-image-section.tsx",
      "registry/brook/blocks/card-image-section/data.json",
      "registry/brook/blocks/card-image-section/components/card-image-section.module.css",
    ],
    path: "@/registry/brook/blocks/card-image-section/page",
  },
  "card-login": {
    name: "card-login",
    type: "block",
    files: [
      "registry/brook/blocks/card-login/page.tsx",
      "registry/brook/blocks/card-login/components/card-login.tsx",
      "registry/brook/blocks/card-login/components/card-login.module.css",
    ],
    path: "@/registry/brook/blocks/card-login/page",
  },
  "card-progress": {
    name: "card-progress",
    type: "block",
    files: [
      "registry/brook/blocks/card-progress/page.tsx",
      "registry/brook/blocks/card-progress/components/progress-card.tsx",
      "registry/brook/blocks/card-progress/components/progress-card.module.css",
    ],
    path: "@/registry/brook/blocks/card-progress/page",
  },
  "card-task": {
    name: "card-task",
    type: "block",
    files: [
      "registry/brook/blocks/card-task/page.tsx",
      "registry/brook/blocks/card-task/components/card-task.tsx",
      "registry/brook/blocks/card-task/components/card-task.module.css",
    ],
    path: "@/registry/brook/blocks/card-task/page",
  },
  "card-traffic": {
    name: "card-traffic",
    type: "block",
    files: [
      "registry/brook/blocks/card-traffic/page.tsx",
      "registry/brook/blocks/card-traffic/components/card-traffic.tsx",
      "registry/brook/blocks/card-traffic/data.json",
      "registry/brook/blocks/card-traffic/components/card-traffic.module.css",
    ],
    path: "@/registry/brook/blocks/card-traffic/page",
  },
  "expandable-card-carousel": {
    name: "expandable-card-carousel",
    type: "block",
    files: [
      "registry/brook/blocks/expandable-card-carousel/page.tsx",
      "registry/brook/blocks/expandable-card-carousel/components/expandable-card-carousel.tsx",
      "registry/brook/blocks/expandable-card-carousel/data.json",
      "registry/brook/blocks/expandable-card-carousel/components/expandable-card-carousel.module.css",
    ],
    path: "@/registry/brook/blocks/expandable-card-carousel/page",
  },
  "kanban-board": {
    name: "kanban-board",
    type: "block",
    files: [
      "registry/brook/blocks/kanban-board/page.tsx",
      "registry/brook/blocks/kanban-board/components/delete-dialog.tsx",
      "registry/brook/blocks/kanban-board/components/filter-bar.tsx",
      "registry/brook/blocks/kanban-board/components/kanban.tsx",
      "registry/brook/blocks/kanban-board/components/priority-icon.tsx",
      "registry/brook/blocks/kanban-board/components/project-board.tsx",
      "registry/brook/blocks/kanban-board/components/task-dialog.tsx",
      "registry/brook/blocks/kanban-board/data.json",
      "registry/brook/blocks/kanban-board/components/kanban.module.css",
      "registry/brook/blocks/kanban-board/hooks/use-kanban-dnd.ts",
      "registry/brook/blocks/kanban-board/hooks/use-task-dialog.ts",
      "registry/brook/blocks/kanban-board/lib/project.ts",
      "registry/brook/blocks/kanban-board/types/index.ts",
    ],
    path: "@/registry/brook/blocks/kanban-board/page",
  },
  "pricing-section": {
    name: "pricing-section",
    type: "block",
    files: [
      "registry/brook/blocks/pricing-section/page.tsx",
      "registry/brook/blocks/pricing-section/components/pricing-section.tsx",
      "registry/brook/blocks/pricing-section/data.json",
      "registry/brook/blocks/pricing-section/components/pricing-section.module.css",
    ],
    path: "@/registry/brook/blocks/pricing-section/page",
  },
  accordion: {
    name: "accordion",
    type: "ui",
    files: ["registry/brook/ui/accordion/accordion.tsx", "registry/brook/ui/accordion/accordion.module.css"],
  },
  alert: {
    name: "alert",
    type: "ui",
    files: ["registry/brook/ui/alert/alert.tsx", "registry/brook/ui/alert/alert.module.css"],
  },
  "alert-dialog": {
    name: "alert-dialog",
    type: "ui",
    files: [
      "registry/brook/ui/alert-dialog/alert-dialog.tsx",
      "registry/brook/ui/alert-dialog/alert-dialog.module.css",
    ],
  },
  "arrow-icon": {
    name: "arrow-icon",
    type: "ui",
    files: ["registry/brook/ui/arrow-icon/arrow-icon.tsx"],
  },
  autocomplete: {
    name: "autocomplete",
    type: "ui",
    files: [
      "registry/brook/ui/autocomplete/autocomplete.tsx",
      "registry/brook/ui/autocomplete/autocomplete.module.css",
    ],
  },
  avatar: {
    name: "avatar",
    type: "ui",
    files: ["registry/brook/ui/avatar/avatar.tsx", "registry/brook/ui/avatar/avatar.module.css"],
  },
  background: {
    name: "background",
    type: "ui",
    files: ["registry/brook/ui/background/background.tsx", "registry/brook/ui/background/background.module.css"],
  },
  badge: {
    name: "badge",
    type: "ui",
    files: ["registry/brook/ui/badge/badge.tsx", "registry/brook/ui/badge/badge.module.css"],
  },
  button: {
    name: "button",
    type: "ui",
    files: ["registry/brook/ui/button/button.tsx", "registry/brook/ui/button/button.module.css"],
  },
  calendar: {
    name: "calendar",
    type: "ui",
    files: ["registry/brook/ui/calendar/calendar.tsx", "registry/brook/ui/calendar/calendar.module.css"],
  },
  card: {
    name: "card",
    type: "ui",
    files: ["registry/brook/ui/card/card.tsx", "registry/brook/ui/card/card.module.css"],
  },
  carousel: {
    name: "carousel",
    type: "ui",
    files: ["registry/brook/ui/carousel/carousel.tsx", "registry/brook/ui/carousel/carousel.module.css"],
  },
  chart: {
    name: "chart",
    type: "ui",
    files: ["registry/brook/ui/chart/chart.tsx", "registry/brook/ui/chart/chart.module.css"],
  },
  checkbox: {
    name: "checkbox",
    type: "ui",
    files: ["registry/brook/ui/checkbox/checkbox.tsx", "registry/brook/ui/checkbox/checkbox.module.css"],
  },
  "checkbox-group": {
    name: "checkbox-group",
    type: "ui",
    files: [
      "registry/brook/ui/checkbox-group/checkbox-group.tsx",
      "registry/brook/ui/checkbox-group/checkbox-group.module.css",
    ],
  },
  collapsible: {
    name: "collapsible",
    type: "ui",
    files: ["registry/brook/ui/collapsible/collapsible.tsx", "registry/brook/ui/collapsible/collapsible.module.css"],
  },
  combobox: {
    name: "combobox",
    type: "ui",
    files: ["registry/brook/ui/combobox/combobox.tsx", "registry/brook/ui/combobox/combobox.module.css"],
  },
  command: {
    name: "command",
    type: "ui",
    files: ["registry/brook/ui/command/command.tsx", "registry/brook/ui/command/command.module.css"],
  },
  "context-menu": {
    name: "context-menu",
    type: "ui",
    files: [
      "registry/brook/ui/context-menu/context-menu.tsx",
      "registry/brook/ui/context-menu/context-menu.module.css",
    ],
  },
  "copy-button": {
    name: "copy-button",
    type: "ui",
    files: ["registry/brook/ui/copy-button/copy-button.tsx", "registry/brook/ui/copy-button/copy-button.module.css"],
  },
  dialog: {
    name: "dialog",
    type: "ui",
    files: ["registry/brook/ui/dialog/dialog.tsx", "registry/brook/ui/dialog/dialog.module.css"],
  },
  "dropdown-menu": {
    name: "dropdown-menu",
    type: "ui",
    files: [
      "registry/brook/ui/dropdown-menu/dropdown-menu.tsx",
      "registry/brook/ui/dropdown-menu/dropdown-menu.module.css",
    ],
  },
  "expandable-card": {
    name: "expandable-card",
    type: "ui",
    files: [
      "registry/brook/ui/expandable-card/expandable-card.tsx",
      "registry/brook/ui/expandable-card/expandable-card.module.css",
    ],
  },
  field: {
    name: "field",
    type: "ui",
    files: ["registry/brook/ui/field/field.tsx", "registry/brook/ui/field/field.module.css"],
  },
  fieldset: {
    name: "fieldset",
    type: "ui",
    files: ["registry/brook/ui/fieldset/fieldset.tsx", "registry/brook/ui/fieldset/fieldset.module.css"],
  },
  form: {
    name: "form",
    type: "ui",
    files: ["registry/brook/ui/form/form.tsx", "registry/brook/ui/form/form.module.css"],
  },
  input: {
    name: "input",
    type: "ui",
    files: ["registry/brook/ui/input/input.tsx", "registry/brook/ui/input/input.module.css"],
  },
  kbd: {
    name: "kbd",
    type: "ui",
    files: ["registry/brook/ui/kbd/kbd.tsx", "registry/brook/ui/kbd/kbd.module.css"],
  },
  "like-button": {
    name: "like-button",
    type: "ui",
    files: ["registry/brook/ui/like-button/like-button.tsx", "registry/brook/ui/like-button/like-button.module.css"],
  },
  menubar: {
    name: "menubar",
    type: "ui",
    files: ["registry/brook/ui/menubar/menubar.tsx", "registry/brook/ui/menubar/menubar.module.css"],
  },
  meter: {
    name: "meter",
    type: "ui",
    files: ["registry/brook/ui/meter/meter.tsx", "registry/brook/ui/meter/meter.module.css"],
  },
  "navigation-menu": {
    name: "navigation-menu",
    type: "ui",
    files: [
      "registry/brook/ui/navigation-menu/navigation-menu.tsx",
      "registry/brook/ui/navigation-menu/navigation-menu.module.css",
    ],
  },
  "number-field": {
    name: "number-field",
    type: "ui",
    files: [
      "registry/brook/ui/number-field/number-field.tsx",
      "registry/brook/ui/number-field/number-field.module.css",
    ],
  },
  popover: {
    name: "popover",
    type: "ui",
    files: ["registry/brook/ui/popover/popover.tsx", "registry/brook/ui/popover/popover.module.css"],
  },
  "preview-card": {
    name: "preview-card",
    type: "ui",
    files: [
      "registry/brook/ui/preview-card/preview-card.tsx",
      "registry/brook/ui/preview-card/preview-card.module.css",
    ],
  },
  progress: {
    name: "progress",
    type: "ui",
    files: ["registry/brook/ui/progress/progress.tsx", "registry/brook/ui/progress/progress.module.css"],
  },
  radio: {
    name: "radio",
    type: "ui",
    files: ["registry/brook/ui/radio/radio.tsx", "registry/brook/ui/radio/radio.module.css"],
  },
  "scroll-area": {
    name: "scroll-area",
    type: "ui",
    files: ["registry/brook/ui/scroll-area/scroll-area.tsx", "registry/brook/ui/scroll-area/scroll-area.module.css"],
  },
  select: {
    name: "select",
    type: "ui",
    files: ["registry/brook/ui/select/select.tsx", "registry/brook/ui/select/select.module.css"],
  },
  separator: {
    name: "separator",
    type: "ui",
    files: ["registry/brook/ui/separator/separator.tsx", "registry/brook/ui/separator/separator.module.css"],
  },
  sidebar: {
    name: "sidebar",
    type: "ui",
    files: ["registry/brook/ui/sidebar/sidebar.tsx", "registry/brook/ui/sidebar/sidebar.module.css"],
  },
  slider: {
    name: "slider",
    type: "ui",
    files: ["registry/brook/ui/slider/slider.tsx", "registry/brook/ui/slider/slider.module.css"],
  },
  switch: {
    name: "switch",
    type: "ui",
    files: ["registry/brook/ui/switch/switch.tsx", "registry/brook/ui/switch/switch.module.css"],
  },
  table: {
    name: "table",
    type: "ui",
    files: ["registry/brook/ui/table/table.tsx", "registry/brook/ui/table/table.module.css"],
  },
  tabs: {
    name: "tabs",
    type: "ui",
    files: ["registry/brook/ui/tabs/tabs.tsx", "registry/brook/ui/tabs/tabs.module.css"],
  },
  toast: {
    name: "toast",
    type: "ui",
    files: ["registry/brook/ui/toast/toast.tsx", "registry/brook/ui/toast/toast.module.css"],
  },
  toggle: {
    name: "toggle",
    type: "ui",
    files: ["registry/brook/ui/toggle/toggle.tsx", "registry/brook/ui/toggle/toggle.module.css"],
  },
  "toggle-group": {
    name: "toggle-group",
    type: "ui",
    files: [
      "registry/brook/ui/toggle-group/toggle-group.tsx",
      "registry/brook/ui/toggle-group/toggle-group.module.css",
    ],
  },
  toolbar: {
    name: "toolbar",
    type: "ui",
    files: ["registry/brook/ui/toolbar/toolbar.tsx", "registry/brook/ui/toolbar/toolbar.module.css"],
  },
  tooltip: {
    name: "tooltip",
    type: "ui",
    files: ["registry/brook/ui/tooltip/tooltip.tsx", "registry/brook/ui/tooltip/tooltip.module.css"],
  },
  "accordion-animation-tailwind": {
    name: "accordion-animation-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/accordion-animation.tsx"],
    path: "@/registry/brook/tailwind/examples/accordion-animation",
  },
  "accordion-demo-tailwind": {
    name: "accordion-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/accordion-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/accordion-demo",
  },
  "accordion-minimal-tailwind": {
    name: "accordion-minimal-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/accordion-minimal.tsx"],
    path: "@/registry/brook/tailwind/examples/accordion-minimal",
  },
  "alert-demo-tailwind": {
    name: "alert-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/alert-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/alert-demo",
  },
  "alert-destructive-tailwind": {
    name: "alert-destructive-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/alert-destructive.tsx"],
    path: "@/registry/brook/tailwind/examples/alert-destructive",
  },
  "alert-dialog-demo-tailwind": {
    name: "alert-dialog-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/alert-dialog-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/alert-dialog-demo",
  },
  "alert-dialog-nested-tailwind": {
    name: "alert-dialog-nested-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/alert-dialog-nested.tsx"],
    path: "@/registry/brook/tailwind/examples/alert-dialog-nested",
  },
  "alert-info-tailwind": {
    name: "alert-info-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/alert-info.tsx"],
    path: "@/registry/brook/tailwind/examples/alert-info",
  },
  "alert-success-tailwind": {
    name: "alert-success-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/alert-success.tsx"],
    path: "@/registry/brook/tailwind/examples/alert-success",
  },
  "alert-warning-tailwind": {
    name: "alert-warning-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/alert-warning.tsx"],
    path: "@/registry/brook/tailwind/examples/alert-warning",
  },
  "autocomplete-auto-highlight-tailwind": {
    name: "autocomplete-auto-highlight-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/autocomplete-auto-highlight.tsx"],
    path: "@/registry/brook/tailwind/examples/autocomplete-auto-highlight",
  },
  "autocomplete-clearable-tailwind": {
    name: "autocomplete-clearable-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/autocomplete-clearable.tsx"],
    path: "@/registry/brook/tailwind/examples/autocomplete-clearable",
  },
  "autocomplete-demo-tailwind": {
    name: "autocomplete-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/autocomplete-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/autocomplete-demo",
  },
  "autocomplete-fuzzy-tailwind": {
    name: "autocomplete-fuzzy-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/autocomplete-fuzzy.tsx"],
    path: "@/registry/brook/tailwind/examples/autocomplete-fuzzy",
  },
  "autocomplete-grouped-tailwind": {
    name: "autocomplete-grouped-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/autocomplete-grouped.tsx"],
    path: "@/registry/brook/tailwind/examples/autocomplete-grouped",
  },
  "avatar-demo-tailwind": {
    name: "avatar-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/avatar-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/avatar-demo",
  },
  "avatar-group-tailwind": {
    name: "avatar-group-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/avatar-group.tsx"],
    path: "@/registry/brook/tailwind/examples/avatar-group",
  },
  "badge-demo-tailwind": {
    name: "badge-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/badge-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/badge-demo",
  },
  "badge-error-tailwind": {
    name: "badge-error-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/badge-error.tsx"],
    path: "@/registry/brook/tailwind/examples/badge-error",
  },
  "badge-success-tailwind": {
    name: "badge-success-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/badge-success.tsx"],
    path: "@/registry/brook/tailwind/examples/badge-success",
  },
  "button-demo-tailwind": {
    name: "button-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/button-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/button-demo",
  },
  "button-destructive-tailwind": {
    name: "button-destructive-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/button-destructive.tsx"],
    path: "@/registry/brook/tailwind/examples/button-destructive",
  },
  "button-disabled-tailwind": {
    name: "button-disabled-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/button-disabled.tsx"],
    path: "@/registry/brook/tailwind/examples/button-disabled",
  },
  "button-external-link-tailwind": {
    name: "button-external-link-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/button-external-link.tsx"],
    path: "@/registry/brook/tailwind/examples/button-external-link",
  },
  "button-ghost-tailwind": {
    name: "button-ghost-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/button-ghost.tsx"],
    path: "@/registry/brook/tailwind/examples/button-ghost",
  },
  "button-icon-tailwind": {
    name: "button-icon-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/button-icon.tsx"],
    path: "@/registry/brook/tailwind/examples/button-icon",
  },
  "button-loading-tailwind": {
    name: "button-loading-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/button-loading.tsx"],
    path: "@/registry/brook/tailwind/examples/button-loading",
  },
  "button-outline-tailwind": {
    name: "button-outline-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/button-outline.tsx"],
    path: "@/registry/brook/tailwind/examples/button-outline",
  },
  "button-secondary-tailwind": {
    name: "button-secondary-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/button-secondary.tsx"],
    path: "@/registry/brook/tailwind/examples/button-secondary",
  },
  "button-with-arrow-tailwind": {
    name: "button-with-arrow-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/button-with-arrow.tsx"],
    path: "@/registry/brook/tailwind/examples/button-with-arrow",
  },
  "card-demo-tailwind": {
    name: "card-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/card-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/card-demo",
  },
  "card-image-demo-tailwind": {
    name: "card-image-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/card-image-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/card-image-demo",
  },
  "carousel-demo-tailwind": {
    name: "carousel-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/carousel-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/carousel-demo",
  },
  "chart-area-demo-tailwind": {
    name: "chart-area-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/chart-area-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/chart-area-demo",
  },
  "chart-bar-demo-tailwind": {
    name: "chart-bar-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/chart-bar-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/chart-bar-demo",
  },
  "chart-line-demo-tailwind": {
    name: "chart-line-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/chart-line-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/chart-line-demo",
  },
  "chart-pie-demo-tailwind": {
    name: "chart-pie-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/chart-pie-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/chart-pie-demo",
  },
  "checkbox-card-tailwind": {
    name: "checkbox-card-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/checkbox-card.tsx"],
    path: "@/registry/brook/tailwind/examples/checkbox-card",
  },
  "checkbox-demo-tailwind": {
    name: "checkbox-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/checkbox-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/checkbox-demo",
  },
  "checkbox-description-tailwind": {
    name: "checkbox-description-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/checkbox-description.tsx"],
    path: "@/registry/brook/tailwind/examples/checkbox-description",
  },
  "checkbox-group-demo-tailwind": {
    name: "checkbox-group-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/checkbox-group-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/checkbox-group-demo",
  },
  "checkbox-group-parent-tailwind": {
    name: "checkbox-group-parent-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/checkbox-group-parent.tsx"],
    path: "@/registry/brook/tailwind/examples/checkbox-group-parent",
  },
  "collapsible-demo-tailwind": {
    name: "collapsible-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/collapsible-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/collapsible-demo",
  },
  "combobox-auto-highlight-tailwind": {
    name: "combobox-auto-highlight-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/combobox-auto-highlight.tsx"],
    path: "@/registry/brook/tailwind/examples/combobox-auto-highlight",
  },
  "combobox-clearable-tailwind": {
    name: "combobox-clearable-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/combobox-clearable.tsx"],
    path: "@/registry/brook/tailwind/examples/combobox-clearable",
  },
  "combobox-demo-tailwind": {
    name: "combobox-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/combobox-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/combobox-demo",
  },
  "combobox-grouped-tailwind": {
    name: "combobox-grouped-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/combobox-grouped.tsx"],
    path: "@/registry/brook/tailwind/examples/combobox-grouped",
  },
  "combobox-multiple-tailwind": {
    name: "combobox-multiple-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/combobox-multiple.tsx"],
    path: "@/registry/brook/tailwind/examples/combobox-multiple",
  },
  "command-demo-tailwind": {
    name: "command-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/command-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/command-demo",
  },
  "context-menu-demo-tailwind": {
    name: "context-menu-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/context-menu-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/context-menu-demo",
  },
  "copy-button-demo-tailwind": {
    name: "copy-button-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/copy-button-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/copy-button-demo",
  },
  "dialog-demo-tailwind": {
    name: "dialog-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/dialog-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/dialog-demo",
  },
  "dialog-motion-tailwind": {
    name: "dialog-motion-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/dialog-motion.tsx"],
    path: "@/registry/brook/tailwind/examples/dialog-motion",
  },
  "dialog-sheet-tailwind": {
    name: "dialog-sheet-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/dialog-sheet.tsx"],
    path: "@/registry/brook/tailwind/examples/dialog-sheet",
  },
  "dropdown-menu-demo-tailwind": {
    name: "dropdown-menu-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/dropdown-menu-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/dropdown-menu-demo",
  },
  "dropdown-menu-motion-tailwind": {
    name: "dropdown-menu-motion-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/dropdown-menu-motion.tsx"],
    path: "@/registry/brook/tailwind/examples/dropdown-menu-motion",
  },
  "dropdown-menu-profile-tailwind": {
    name: "dropdown-menu-profile-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/dropdown-menu-profile.tsx"],
    path: "@/registry/brook/tailwind/examples/dropdown-menu-profile",
  },
  "dropdown-menu-submenu-tailwind": {
    name: "dropdown-menu-submenu-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/dropdown-menu-submenu.tsx"],
    path: "@/registry/brook/tailwind/examples/dropdown-menu-submenu",
  },
  "expandable-card-demo-tailwind": {
    name: "expandable-card-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/expandable-card-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/expandable-card-demo",
  },
  "field-demo-tailwind": {
    name: "field-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/field-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/field-demo",
  },
  "fieldset-demo-tailwind": {
    name: "fieldset-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/fieldset-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/fieldset-demo",
  },
  "form-demo-tailwind": {
    name: "form-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/form-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/form-demo",
  },
  "input-demo-tailwind": {
    name: "input-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/input-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/input-demo",
  },
  "like-button-demo-tailwind": {
    name: "like-button-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/like-button-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/like-button-demo",
  },
  "menubar-demo-tailwind": {
    name: "menubar-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/menubar-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/menubar-demo",
  },
  "meter-demo-tailwind": {
    name: "meter-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/meter-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/meter-demo",
  },
  "navigation-menu-demo-tailwind": {
    name: "navigation-menu-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/navigation-menu-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/navigation-menu-demo",
  },
  "navigation-sub-menu-tailwind": {
    name: "navigation-sub-menu-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/navigation-sub-menu.tsx"],
    path: "@/registry/brook/tailwind/examples/navigation-sub-menu",
  },
  "number-field-demo-tailwind": {
    name: "number-field-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/number-field-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/number-field-demo",
  },
  "popover-animated-tailwind": {
    name: "popover-animated-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/popover-animated.tsx"],
    path: "@/registry/brook/tailwind/examples/popover-animated",
  },
  "popover-demo-tailwind": {
    name: "popover-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/popover-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/popover-demo",
  },
  "preview-card-demo-tailwind": {
    name: "preview-card-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/preview-card-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/preview-card-demo",
  },
  "progress-demo-tailwind": {
    name: "progress-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/progress-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/progress-demo",
  },
  "radio-demo-tailwind": {
    name: "radio-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/radio-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/radio-demo",
  },
  "scroll-area-demo-tailwind": {
    name: "scroll-area-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/scroll-area-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/scroll-area-demo",
  },
  "select-demo-tailwind": {
    name: "select-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/select-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/select-demo",
  },
  "separator-demo-tailwind": {
    name: "separator-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/separator-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/separator-demo",
  },
  shippingTailwind: {
    name: "shipping-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/shipping.tsx"],
    path: "@/registry/brook/tailwind/examples/shipping",
  },
  "slider-demo-tailwind": {
    name: "slider-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/slider-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/slider-demo",
  },
  "switch-demo-tailwind": {
    name: "switch-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/switch-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/switch-demo",
  },
  "switch-with-label-tailwind": {
    name: "switch-with-label-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/switch-with-label.tsx"],
    path: "@/registry/brook/tailwind/examples/switch-with-label",
  },
  "table-demo-tailwind": {
    name: "table-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/table-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/table-demo",
  },
  "tabs-demo-tailwind": {
    name: "tabs-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/tabs-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/tabs-demo",
  },
  "tabs-motion-tailwind": {
    name: "tabs-motion-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/tabs-motion.tsx"],
    path: "@/registry/brook/tailwind/examples/tabs-motion",
  },
  "tabs-vertical-tailwind": {
    name: "tabs-vertical-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/tabs-vertical.tsx"],
    path: "@/registry/brook/tailwind/examples/tabs-vertical",
  },
  "toast-demo-tailwind": {
    name: "toast-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/toast-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/toast-demo",
  },
  "toggle-demo-tailwind": {
    name: "toggle-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/toggle-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/toggle-demo",
  },
  "toggle-group-demo-tailwind": {
    name: "toggle-group-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/toggle-group-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/toggle-group-demo",
  },
  "toolbar-demo-tailwind": {
    name: "toolbar-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/toolbar-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/toolbar-demo",
  },
  "tooltip-demo-tailwind": {
    name: "tooltip-demo-tailwind",
    type: "example",
    files: ["registry/brook/tailwind/examples/tooltip-demo.tsx"],
    path: "@/registry/brook/tailwind/examples/tooltip-demo",
  },
  "ai-chat-tailwind": {
    name: "ai-chat-tailwind",
    type: "block",
    files: [
      "registry/brook/tailwind/blocks/ai-chat/page.tsx",
      "registry/brook/tailwind/blocks/ai-chat/components/ai-chat.tsx",
    ],
    path: "@/registry/brook/tailwind/blocks/ai-chat/page",
  },
  "card-image-section-tailwind": {
    name: "card-image-section-tailwind",
    type: "block",
    files: [
      "registry/brook/tailwind/blocks/card-image-section/page.tsx",
      "registry/brook/tailwind/blocks/card-image-section/components/card-image-section.tsx",
      "registry/brook/tailwind/blocks/card-image-section/data.json",
    ],
    path: "@/registry/brook/tailwind/blocks/card-image-section/page",
  },
  "card-login-tailwind": {
    name: "card-login-tailwind",
    type: "block",
    files: [
      "registry/brook/tailwind/blocks/card-login/page.tsx",
      "registry/brook/tailwind/blocks/card-login/components/card-login.tsx",
    ],
    path: "@/registry/brook/tailwind/blocks/card-login/page",
  },
  "card-progress-tailwind": {
    name: "card-progress-tailwind",
    type: "block",
    files: [
      "registry/brook/tailwind/blocks/card-progress/page.tsx",
      "registry/brook/tailwind/blocks/card-progress/components/progress-card.tsx",
    ],
    path: "@/registry/brook/tailwind/blocks/card-progress/page",
  },
  "card-task-tailwind": {
    name: "card-task-tailwind",
    type: "block",
    files: [
      "registry/brook/tailwind/blocks/card-task/page.tsx",
      "registry/brook/tailwind/blocks/card-task/components/card-task.tsx",
    ],
    path: "@/registry/brook/tailwind/blocks/card-task/page",
  },
  "card-traffic-tailwind": {
    name: "card-traffic-tailwind",
    type: "block",
    files: [
      "registry/brook/tailwind/blocks/card-traffic/page.tsx",
      "registry/brook/tailwind/blocks/card-traffic/components/card-traffic.tsx",
      "registry/brook/tailwind/blocks/card-traffic/data.json",
    ],
    path: "@/registry/brook/tailwind/blocks/card-traffic/page",
  },
  "expandable-card-carousel-tailwind": {
    name: "expandable-card-carousel-tailwind",
    type: "block",
    files: [
      "registry/brook/tailwind/blocks/expandable-card-carousel/page.tsx",
      "registry/brook/tailwind/blocks/expandable-card-carousel/components/expandable-card-carousel.tsx",
      "registry/brook/tailwind/blocks/expandable-card-carousel/data.json",
    ],
    path: "@/registry/brook/tailwind/blocks/expandable-card-carousel/page",
  },
  "kanban-board-tailwind": {
    name: "kanban-board-tailwind",
    type: "block",
    files: [
      "registry/brook/tailwind/blocks/kanban-board/page.tsx",
      "registry/brook/tailwind/blocks/kanban-board/components/delete-dialog.tsx",
      "registry/brook/tailwind/blocks/kanban-board/components/filter-bar.tsx",
      "registry/brook/tailwind/blocks/kanban-board/components/kanban.tsx",
      "registry/brook/tailwind/blocks/kanban-board/components/priority-icon.tsx",
      "registry/brook/tailwind/blocks/kanban-board/components/project-board.tsx",
      "registry/brook/tailwind/blocks/kanban-board/components/task-dialog.tsx",
      "registry/brook/tailwind/blocks/kanban-board/data.json",
      "registry/brook/tailwind/blocks/kanban-board/hooks/use-kanban-dnd.ts",
      "registry/brook/tailwind/blocks/kanban-board/hooks/use-task-dialog.ts",
      "registry/brook/tailwind/blocks/kanban-board/lib/project.ts",
      "registry/brook/tailwind/blocks/kanban-board/types/index.ts",
    ],
    path: "@/registry/brook/tailwind/blocks/kanban-board/page",
  },
  "pricing-section-tailwind": {
    name: "pricing-section-tailwind",
    type: "block",
    files: [
      "registry/brook/tailwind/blocks/pricing-section/page.tsx",
      "registry/brook/tailwind/blocks/pricing-section/components/pricing-section.tsx",
      "registry/brook/tailwind/blocks/pricing-section/data.json",
    ],
    path: "@/registry/brook/tailwind/blocks/pricing-section/page",
  },
  accordionTailwind: {
    name: "accordion-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/accordion.tsx"],
  },
  "alert-dialog-tailwind": {
    name: "alert-dialog-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/alert-dialog.tsx"],
  },
  alertTailwind: {
    name: "alert-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/alert.tsx"],
  },
  autocompleteTailwind: {
    name: "autocomplete-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/autocomplete.tsx"],
  },
  avatarTailwind: {
    name: "avatar-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/avatar.tsx"],
  },
  backgroundTailwind: {
    name: "background-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/background.tsx"],
  },
  badgeTailwind: {
    name: "badge-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/badge.tsx"],
  },
  buttonTailwind: {
    name: "button-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/button.tsx"],
  },
  calendarTailwind: {
    name: "calendar-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/calendar.tsx"],
  },
  cardTailwind: {
    name: "card-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/card.tsx"],
  },
  carouselTailwind: {
    name: "carousel-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/carousel.tsx"],
  },
  chartTailwind: {
    name: "chart-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/chart.tsx"],
  },
  "checkbox-group-tailwind": {
    name: "checkbox-group-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/checkbox-group.tsx"],
  },
  checkboxTailwind: {
    name: "checkbox-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/checkbox.tsx"],
  },
  collapsibleTailwind: {
    name: "collapsible-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/collapsible.tsx"],
  },
  comboboxTailwind: {
    name: "combobox-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/combobox.tsx"],
  },
  commandTailwind: {
    name: "command-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/command.tsx"],
  },
  "context-menu-tailwind": {
    name: "context-menu-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/context-menu.tsx"],
  },
  "copy-button-tailwind": {
    name: "copy-button-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/copy-button.tsx"],
  },
  dialogTailwind: {
    name: "dialog-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/dialog.tsx"],
  },
  "dropdown-menu-tailwind": {
    name: "dropdown-menu-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/dropdown-menu.tsx"],
  },
  "expandable-card-tailwind": {
    name: "expandable-card-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/expandable-card.tsx"],
  },
  fieldTailwind: {
    name: "field-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/field.tsx"],
  },
  fieldsetTailwind: {
    name: "fieldset-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/fieldset.tsx"],
  },
  formTailwind: {
    name: "form-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/form.tsx"],
  },
  inputTailwind: {
    name: "input-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/input.tsx"],
  },
  kbdTailwind: {
    name: "kbd-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/kbd.tsx"],
  },
  "like-button-tailwind": {
    name: "like-button-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/like-button.tsx"],
  },
  menubarTailwind: {
    name: "menubar-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/menubar.tsx"],
  },
  meterTailwind: {
    name: "meter-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/meter.tsx"],
  },
  "navigation-menu-tailwind": {
    name: "navigation-menu-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/navigation-menu.tsx"],
  },
  "number-field-tailwind": {
    name: "number-field-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/number-field.tsx"],
  },
  popoverTailwind: {
    name: "popover-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/popover.tsx"],
  },
  "preview-card-tailwind": {
    name: "preview-card-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/preview-card.tsx"],
  },
  progressTailwind: {
    name: "progress-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/progress.tsx"],
  },
  radioTailwind: {
    name: "radio-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/radio.tsx"],
  },
  "scroll-area-tailwind": {
    name: "scroll-area-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/scroll-area.tsx"],
  },
  selectTailwind: {
    name: "select-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/select.tsx"],
  },
  separatorTailwind: {
    name: "separator-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/separator.tsx"],
  },
  sliderTailwind: {
    name: "slider-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/slider.tsx"],
  },
  switchTailwind: {
    name: "switch-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/switch.tsx"],
  },
  tableTailwind: {
    name: "table-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/table.tsx"],
  },
  tabsTailwind: {
    name: "tabs-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/tabs.tsx"],
  },
  toastTailwind: {
    name: "toast-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/toast.tsx"],
  },
  "toggle-group-tailwind": {
    name: "toggle-group-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/toggle-group.tsx"],
  },
  toggleTailwind: {
    name: "toggle-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/toggle.tsx"],
  },
  toolbarTailwind: {
    name: "toolbar-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/toolbar.tsx"],
  },
  tooltipTailwind: {
    name: "tooltip-tailwind",
    type: "ui",
    files: ["registry/brook/tailwind/ui/tooltip.tsx"],
  },
};
