// @generated
// This file is autogenerated by scripts/build-registry-index.ts
// Do not edit this file directly.
// @ts-nocheck
import type { ComponentType } from "react";
import { lazy } from "react";

type RegistryEntry = {
  name: string;
  type: "example" | "block";
  component: ComponentType;
};

export const Index: Record<string, RegistryEntry> = {
  "accordion-demo": {
    name: "accordion-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/accordion-demo");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "accordion-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "accordion-motion": {
    name: "accordion-motion",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/accordion-motion/accordion-motion"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "accordion-motion";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "alert-demo": {
    name: "alert-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/alert-demo/alert-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "alert-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "alert-destructive": {
    name: "alert-destructive",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/alert-destructive/alert-destructive"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "alert-destructive";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "alert-dialog-demo": {
    name: "alert-dialog-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/alert-dialog-demo");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "alert-dialog-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "alert-info": {
    name: "alert-info",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/alert-info/alert-info"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "alert-info";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "alert-success": {
    name: "alert-success",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/alert-success/alert-success"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "alert-success";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "alert-warning": {
    name: "alert-warning",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/alert-warning/alert-warning"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "alert-warning";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "autocomplete-demo": {
    name: "autocomplete-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/autocomplete-demo/autocomplete-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "autocomplete-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "avatar-demo": {
    name: "avatar-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/avatar-demo");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "avatar-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "avatar-motion": {
    name: "avatar-motion",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/avatar-motion/avatar-motion"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "avatar-motion";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "background-demo": {
    name: "background-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/background-demo/background-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "background-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "badge-demo": {
    name: "badge-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/badge-demo/badge-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "badge-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "badge-error-motion": {
    name: "badge-error-motion",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/badge-error-motion/badge-error-motion"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "badge-error-motion";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "badge-external-links": {
    name: "badge-external-links",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/badge-external-links/badge-external-links"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "badge-external-links";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "badge-sizes": {
    name: "badge-sizes",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/badge-sizes/badge-sizes"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "badge-sizes";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "badge-success-motion": {
    name: "badge-success-motion",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/badge-success-motion/badge-success-motion"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "badge-success-motion";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "badge-variants": {
    name: "badge-variants",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/badge-variants/badge-variants"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "badge-variants";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "button-demo": {
    name: "button-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/button-demo");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "button-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "button-destructive": {
    name: "button-destructive",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/button-destructive");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "button-destructive";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "button-disabled": {
    name: "button-disabled",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/button-disabled");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "button-disabled";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "button-external-link": {
    name: "button-external-link",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/button-external-link"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "button-external-link";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "button-ghost": {
    name: "button-ghost",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/button-ghost");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "button-ghost";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "button-loading": {
    name: "button-loading",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/button-loading/button-loading"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "button-loading";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "button-outline": {
    name: "button-outline",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/button-outline");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "button-outline";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "button-secondary": {
    name: "button-secondary",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/button-secondary");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "button-secondary";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "button-sizes": {
    name: "button-sizes",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/button-sizes/button-sizes"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "button-sizes";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "button-with-arrow": {
    name: "button-with-arrow",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/button-with-arrow");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "button-with-arrow";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "card-demo": {
    name: "card-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/card-demo/card-demo");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "card-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "card-pricing-card": {
    name: "card-pricing-card",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/card-pricing-card/card-pricing-card"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "card-pricing-card";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "card-settings": {
    name: "card-settings",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/card-settings/card-settings"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "card-settings";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "carousel-demo": {
    name: "carousel-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/carousel-demo/carousel-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "carousel-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "chart-area-demo": {
    name: "chart-area-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/chart-area-demo/chart-area-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "chart-area-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "chart-bar-demo": {
    name: "chart-bar-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/chart-bar-demo/chart-bar-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "chart-bar-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "chart-line-demo": {
    name: "chart-line-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/chart-line-demo/chart-line-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "chart-line-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "chart-pie-demo": {
    name: "chart-pie-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/chart-pie-demo/chart-pie-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "chart-pie-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "checkbox-demo": {
    name: "checkbox-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/checkbox-demo/checkbox-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "checkbox-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "checkbox-group-demo": {
    name: "checkbox-group-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/checkbox-group-demo/checkbox-group-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "checkbox-group-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "collapsible-demo": {
    name: "collapsible-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/collapsible-demo/collapsible-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "collapsible-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "combobox-demo": {
    name: "combobox-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/combobox-demo/combobox-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "combobox-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "command-demo": {
    name: "command-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/command-demo/command-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "command-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "context-menu-demo": {
    name: "context-menu-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/context-menu-demo/context-menu-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "context-menu-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "copy-button-demo": {
    name: "copy-button-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/copy-button-demo");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "copy-button-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "dialog-demo": {
    name: "dialog-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/dialog-demo/dialog-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "dialog-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "dialog-motion": {
    name: "dialog-motion",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/dialog-motion/dialog-motion"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "dialog-motion";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "dropdown-menu-demo": {
    name: "dropdown-menu-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/dropdown-menu-demo/dropdown-menu-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "dropdown-menu-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "dropdown-menu-motion": {
    name: "dropdown-menu-motion",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/dropdown-menu-motion/dropdown-menu-motion"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "dropdown-menu-motion";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "dropdown-menu-submenu": {
    name: "dropdown-menu-submenu",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/dropdown-menu-submenu"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "dropdown-menu-submenu";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "expandable-card-demo": {
    name: "expandable-card-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/expandable-card-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "expandable-card-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "field-demo": {
    name: "field-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/field-demo/field-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "field-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "fieldset-demo": {
    name: "fieldset-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/fieldset-demo/fieldset-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "fieldset-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "form-demo": {
    name: "form-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/form-demo");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "form-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "input-demo": {
    name: "input-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/input-demo/input-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "input-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "like-button-demo": {
    name: "like-button-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/like-button-demo");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "like-button-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "menubar-demo": {
    name: "menubar-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/menubar-demo/menubar-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "menubar-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "meter-demo": {
    name: "meter-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/meter-demo/meter-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "meter-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "navigation-menu-demo": {
    name: "navigation-menu-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/navigation-menu-demo/navigation-menu-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "navigation-menu-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "navigation-sub-menu": {
    name: "navigation-sub-menu",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/navigation-sub-menu/navigation-sub-menu"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "navigation-sub-menu";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "number-field-demo": {
    name: "number-field-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/number-field-demo/number-field-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "number-field-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "popover-demo": {
    name: "popover-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/popover-demo/popover-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "popover-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "preview-card-demo": {
    name: "preview-card-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/preview-card-demo/preview-card-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "preview-card-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "progress-demo": {
    name: "progress-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/progress-demo/progress-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "progress-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "radio-demo": {
    name: "radio-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/radio-demo/radio-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "radio-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "scroll-area-demo": {
    name: "scroll-area-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/scroll-area-demo/scroll-area-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "scroll-area-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "select-demo": {
    name: "select-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/select-demo/select-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "select-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  shipping: {
    name: "shipping",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/shipping/shipping");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "shipping";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "slider-demo": {
    name: "slider-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/slider-demo/slider-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "slider-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "switch-demo": {
    name: "switch-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/switch-demo/switch-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "switch-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "switch-with-label": {
    name: "switch-with-label",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/switch-with-label/switch-with-label"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "switch-with-label";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "tabs-demo": {
    name: "tabs-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/tabs-demo/tabs-demo");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "tabs-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "tabs-motion": {
    name: "tabs-motion",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/tabs-motion/tabs-motion"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "tabs-motion";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "tabs-vertical": {
    name: "tabs-vertical",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/tabs-vertical");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "tabs-vertical";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "toast-demo": {
    name: "toast-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/toast-demo");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "toast-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "toggle-demo": {
    name: "toggle-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/toggle-demo");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "toggle-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "toggle-group-demo": {
    name: "toggle-group-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/examples/toggle-group-demo/toggle-group-demo"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "toggle-group-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "toolbar-demo": {
    name: "toolbar-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/toolbar-demo");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "toolbar-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "tooltip-demo": {
    name: "tooltip-demo",
    type: "example",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/examples/tooltip-demo");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "tooltip-demo";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "ai-chat": {
    name: "ai-chat",
    type: "block",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/blocks/ai-chat/ai-chat");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "ai-chat";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "card-history": {
    name: "card-history",
    type: "block",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/blocks/card-history/card-history"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "card-history";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "card-image": {
    name: "card-image",
    type: "block",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/blocks/card-image/card-image");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "card-image";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "card-login": {
    name: "card-login",
    type: "block",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/blocks/card-login/card-login");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "card-login";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "card-task": {
    name: "card-task",
    type: "block",
    component: lazy(async () => {
      const mod = await import("@/registry/brook/blocks/card-task/card-task");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "card-task";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "card-traffic": {
    name: "card-traffic",
    type: "block",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/blocks/card-traffic/card-traffic"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "card-traffic";
      return { default: mod.default || mod[exportName] };
    }),
  },
  "expandable-card": {
    name: "expandable-card",
    type: "block",
    component: lazy(async () => {
      const mod = await import(
        "@/registry/brook/blocks/expandable-card/expandable-card"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "expandable-card";
      return { default: mod.default || mod[exportName] };
    }),
  },
};
