/**
 * Lightweight manifest of all pages
 * This file contains only metadata, no MDX content
 * Used for generating static params and listing pages without loading MDX bundles
 *
 * @generated by scripts/build-source-manifest.ts
 * Do not edit this file directly - edit the meta.json files instead
 */

export type PageMetadata = {
  slug: string[];
  url: string;
  title: string;
  description?: string;
  links?: {
    doc?: string;
    api?: string;
  };
  components?: string[];
  motion?: boolean;
};

export const pagesManifest: PageMetadata[] = [
  {
    slug: [],
    url: "/docs",
    title: "About Roi UI",
    description: "Roi UI is an open source ui library.",
  },
  {
    slug: ["components"],
    url: "/docs/components",
    title: "Components",
    description: "Browse all UI components and blocks available in Roi UI.",
  },
  {
    slug: ["start"],
    url: "/docs/start",
    title: "Quick Start",
    description: "Get started with roi-ui components in minutes",
  },
  {
    slug: ["blocks", "ai-chat"],
    url: "/docs/blocks/ai-chat",
    title: "AI Chat",
    description: "Chat component with AI mode selector",
  },
  {
    slug: ["blocks", "card-expandable"],
    url: "/docs/blocks/card-expandable",
    title: "Expandable Card",
    description: "A linear inspired drawer modal with expansion animation",
  },
  {
    slug: ["blocks", "card-history"],
    url: "/docs/blocks/card-history",
    title: "Transaction History",
    description: "Transaction history card component",
  },
  {
    slug: ["blocks", "card-image"],
    url: "/docs/blocks/card-image",
    title: "Image Card",
    description: "A card component with an image display",
  },
  {
    slug: ["blocks", "card-login"],
    url: "/docs/blocks/card-login",
    title: "Login Card",
    description: "A card component styled for login forms",
  },
  {
    slug: ["blocks", "card-task"],
    url: "/docs/blocks/card-task",
    title: "Task Card",
    description: "Task management card component",
  },
  {
    slug: ["blocks", "card-traffic"],
    url: "/docs/blocks/card-traffic",
    title: "Website Traffic",
    description: "Website traffic analytics card with line chart",
  },
  {
    slug: ["blocks", "profile-menu"],
    url: "/docs/blocks/profile-menu",
    title: "Profile Menu",
    description: "A dropdown menu component for user profile management",
  },
  {
    slug: ["ui", "accordion"],
    url: "/docs/ui/accordion",
    title: "Accordion",
    description:
      "A component that expands or collapses vertically stacked content.",
    links: {
      doc: "https://base-ui.com/react/components/accordion",
      api: "https://base-ui.com/react/components/accordion#api-reference",
    },
  },
  {
    slug: ["ui", "alert"],
    url: "/docs/ui/alert",
    title: "Alert",
    description: "A component for displaying important messages to users.",
  },
  {
    slug: ["ui", "alert-dialog"],
    url: "/docs/ui/alert-dialog",
    title: "Alert Dialog",
    description: "A modal dialog that requires user response to proceed.",
    links: {
      doc: "https://base-ui.com/react/components/alert-dialog",
      api: "https://base-ui.com/react/components/alert-dialog#api-reference",
    },
  },
  {
    slug: ["ui", "autocomplete"],
    url: "/docs/ui/autocomplete",
    title: "Autocomplete",
    description: "An input that suggests options as you type.",
    links: {
      doc: "https://base-ui.com/react/components/autocomplete",
      api: "https://base-ui.com/react/components/autocomplete#api-reference",
    },
  },
  {
    slug: ["ui", "avatar"],
    url: "/docs/ui/avatar",
    title: "Avatar",
    description:
      "An avatar component for displaying user profile pictures, initials, or fallback content.",
    links: {
      doc: "https://base-ui.com/react/components/avatar",
      api: "https://base-ui.com/react/components/avatar#api-reference",
    },
  },
  {
    slug: ["ui", "badge"],
    url: "/docs/ui/badge",
    title: "Badge",
    description:
      "A small status descriptor for UI elements, commonly used for external links and labels.",
  },
  {
    slug: ["ui", "button"],
    url: "/docs/ui/button",
    title: "Button",
    description:
      "A versatile button component with multiple variants and sizes.",
  },
  {
    slug: ["ui", "card"],
    url: "/docs/ui/card",
    title: "Card",
    description:
      "A versatile card component with header, content, footer, and image support",
  },
  {
    slug: ["ui", "carousel"],
    url: "/docs/ui/carousel",
    title: "Carousel",
    description:
      "A composable card carousel with horizontal scroll, keyboard and button navigation.",
  },
  {
    slug: ["ui", "charts"],
    url: "/docs/ui/charts",
    title: "Charts",
    description:
      "Composable chart components for data visualization using Recharts",
    links: {
      doc: "https://recharts.org/",
      api: "https://recharts.github.io/en-US/api/",
    },
  },
  {
    slug: ["ui", "checkbox"],
    url: "/docs/ui/checkbox",
    title: "Checkbox",
    description:
      "A control that allows users to select one or more options from a set.",
    links: {
      doc: "https://base-ui.com/react/components/checkbox",
      api: "https://base-ui.com/react/components/checkbox#api-reference",
    },
  },
  {
    slug: ["ui", "checkbox-group"],
    url: "/docs/ui/checkbox-group",
    title: "Checkbox Group",
    description:
      "A set of checkboxes with shared state management for selecting multiple options.",
    links: {
      doc: "https://base-ui.com/react/components/checkbox-group",
      api: "https://base-ui.com/react/components/checkbox-group#api-reference",
    },
  },
  {
    slug: ["ui", "collapsible"],
    url: "/docs/ui/collapsible",
    title: "Collapsible",
    description: "An expandable/collapsible panel controlled by a button.",
    links: {
      doc: "https://base-ui.com/react/components/collapsible",
      api: "https://base-ui.com/react/components/collapsible#api-reference",
    },
  },
  {
    slug: ["ui", "combobox"],
    url: "/docs/ui/combobox",
    title: "Combobox",
    description:
      "Filterable select for choosing from a predefined list of items.",
    links: {
      doc: "https://base-ui.com/react/components/combobox",
      api: "https://base-ui.com/react/components/combobox#api-reference",
    },
  },
  {
    slug: ["ui", "command"],
    url: "/docs/ui/command",
    title: "Command",
    description:
      "A command menu component for command interfaces. Built with cmdk.",
    links: {
      doc: "https://github.com/pacocoursey/cmdk",
      api: "https://www.npmjs.com/package/cmdk",
    },
  },
  {
    slug: ["ui", "context-menu"],
    url: "/docs/ui/context-menu",
    title: "Context Menu",
    description: "A menu component triggered by right-click or long press.",
    links: {
      doc: "https://base-ui.com/react/components/context-menu",
      api: "https://base-ui.com/react/components/context-menu#api-reference",
    },
  },
  {
    slug: ["ui", "copy-button"],
    url: "/docs/ui/copy-button",
    title: "Copy Button",
    description:
      "A button component with animated copy-to-clipboard functionality.",
  },
  {
    slug: ["ui", "dialog"],
    url: "/docs/ui/dialog",
    title: "Dialog",
    description:
      "A modal dialog component for displaying content in an overlay.",
    links: {
      doc: "https://base-ui.com/react/components/dialog",
      api: "https://base-ui.com/react/components/dialog#api-reference",
    },
  },
  {
    slug: ["ui", "dropdown-menu"],
    url: "/docs/ui/dropdown-menu",
    title: "Dropdown Menu",
    description: "A dropdown menu to display actions.",
    links: {
      doc: "https://base-ui.com/react/components/menu",
      api: "https://base-ui.com/react/components/menu#api-reference",
    },
  },
  {
    slug: ["ui", "field"],
    url: "/docs/ui/field",
    title: "Field",
    description:
      "A complete form field component with label, description, and error handling.",
    links: {
      doc: "https://base-ui.com/react/components/field",
      api: "https://base-ui.com/react/components/field#api-reference",
    },
  },
  {
    slug: ["ui", "fieldset"],
    url: "/docs/ui/fieldset",
    title: "Fieldset",
    description: "A native fieldset element with an easily stylable legend.",
    links: {
      doc: "https://base-ui.com/react/components/fieldset",
      api: "https://base-ui.com/react/components/fieldset#api-reference",
    },
  },
  {
    slug: ["ui", "form"],
    url: "/docs/ui/form",
    title: "Form",
    description:
      "A form component that provides validation and error handling for form inputs.",
    links: {
      doc: "https://base-ui.com/react/components/form",
      api: "https://base-ui.com/react/components/form#api-reference",
    },
  },
  {
    slug: ["ui", "input"],
    url: "/docs/ui/input",
    title: "Input",
    description: "An input field.",
    links: {
      doc: "https://base-ui.com/react/components/input",
      api: "https://base-ui.com/react/components/input#api-reference",
    },
  },
  {
    slug: ["ui", "like-button"],
    url: "/docs/ui/like-button",
    title: "Like Button",
    description:
      "Netflix inspired animated like button component with particle effects.",
  },
  {
    slug: ["ui", "menubar"],
    url: "/docs/ui/menubar",
    title: "Menubar",
    description:
      "A menubar component that provides a horizontal interface for applications.",
    links: {
      doc: "https://base-ui.com/react/components/menubar",
      api: "https://base-ui.com/react/components/menubar#api-reference",
    },
  },
  {
    slug: ["ui", "meter"],
    url: "/docs/ui/meter",
    title: "Meter",
    description: "A graphical display of a numeric value within a range.",
    links: {
      doc: "https://base-ui.com/react/components/meter",
      api: "https://base-ui.com/react/components/meter#api-reference",
    },
  },
  {
    slug: ["ui", "navigation-menu"],
    url: "/docs/ui/navigation-menu",
    title: "Navigation Menu",
    description: "A navigation menu linking to diffrent pages.",
    links: {
      doc: "https://base-ui.com/react/components/navigation-menu",
      api: "https://base-ui.com/react/components/navigation-menu#api-reference",
    },
  },
  {
    slug: ["ui", "number-field"],
    url: "/docs/ui/number-field",
    title: "Number Field",
    description:
      "A numeric input element with increment/decrement buttons and a scrub area.",
    links: {
      doc: "https://base-ui.com/react/components/number-field",
      api: "https://base-ui.com/react/components/number-field#api-reference",
    },
  },
  {
    slug: ["ui", "popover"],
    url: "/docs/ui/popover",
    title: "Popover",
    description:
      "A component for displaying contextual information or actions in a floating panel.",
    links: {
      doc: "https://base-ui.com/react/components/popover",
      api: "https://base-ui.com/react/components/popover#api-reference",
    },
  },
  {
    slug: ["ui", "preview-card"],
    url: "/docs/ui/preview-card",
    title: "Preview Card",
    description:
      "A popup that appears when a link is hovered, showing a preview for sighted users.",
    links: {
      doc: "https://base-ui.com/react/components/preview-card",
      api: "https://base-ui.com/react/components/preview-card#api-reference",
    },
  },
  {
    slug: ["ui", "progress"],
    url: "/docs/ui/progress",
    title: "Progress",
    description: "Displays the status of a task that takes a long time.",
    links: {
      doc: "https://base-ui.com/react/components/progress",
      api: "https://base-ui.com/react/components/progress#api-reference",
    },
  },
  {
    slug: ["ui", "radio"],
    url: "/docs/ui/radio",
    title: "Radio",
    description:
      "A customizable radio button component for selecting one option from a group.",
    links: {
      doc: "https://base-ui.com/react/components/radio",
      api: "https://base-ui.com/react/components/radio#api-reference",
    },
  },
  {
    slug: ["ui", "scroll-area"],
    url: "/docs/ui/scroll-area",
    title: "Scroll Area",
    description: "A native scroll container with custom scrollbars.",
    links: {
      doc: "https://base-ui.com/react/components/scroll-area",
      api: "https://base-ui.com/react/components/scroll-area#api-reference",
    },
  },
  {
    slug: ["ui", "select"],
    url: "/docs/ui/select",
    title: "Select",
    description:
      "A customizable select component for choosing from a list of options.",
    links: {
      doc: "https://base-ui.com/react/components/select",
      api: "https://base-ui.com/react/components/select#api-reference",
    },
  },
  {
    slug: ["ui", "separator"],
    url: "/docs/ui/separator",
    title: "Separator",
    description: "A separator element accessible to screen readers.",
    links: {
      doc: "https://base-ui.com/react/components/separator",
      api: "https://base-ui.com/react/components/separator#api-reference",
    },
  },
  {
    slug: ["ui", "slider"],
    url: "/docs/ui/slider",
    title: "Slider",
    description: "A slider component for selecting values from a range.",
    links: {
      doc: "https://base-ui.com/react/components/slider",
      api: "https://base-ui.com/react/components/slider#api-reference",
    },
  },
  {
    slug: ["ui", "switch"],
    url: "/docs/ui/switch",
    title: "Switch",
    description: "A component to toggle states.",
    links: {
      doc: "https://base-ui.com/react/components/switch",
      api: "https://base-ui.com/react/components/switch#api-reference",
    },
  },
  {
    slug: ["ui", "tabs"],
    url: "/docs/ui/tabs",
    title: "Tabs",
    description:
      "A set of layered sections of content that are displayed one at a time.",
    links: {
      doc: "https://base-ui.com/react/components/tabs",
      api: "https://base-ui.com/react/components/tabs#api-reference",
    },
  },
  {
    slug: ["ui", "toast"],
    url: "/docs/ui/toast",
    title: "Toast",
    description: "A toast notification component.",
    links: {
      doc: "https://base-ui.com/react/components/toast",
      api: "https://base-ui.com/react/components/toast#api-reference",
    },
  },
  {
    slug: ["ui", "toggle"],
    url: "/docs/ui/toggle",
    title: "Toggle",
    description: "A two-state button that can be turned on or off.",
    links: {
      doc: "https://base-ui.com/react/components/toggle",
      api: "https://base-ui.com/react/components/toggle#api-reference",
    },
  },
  {
    slug: ["ui", "toggle-group"],
    url: "/docs/ui/toggle-group",
    title: "Toggle Group",
    description:
      "A set of two-state buttons that can be toggled on or off with shared state management.",
    links: {
      doc: "https://base-ui.com/react/components/toggle-group",
      api: "https://base-ui.com/react/components/toggle-group#api-reference",
    },
  },
  {
    slug: ["ui", "toolbar"],
    url: "/docs/ui/toolbar",
    title: "Toolbar",
    description:
      "A container for grouping a set of buttons and controls with keyboard navigation support.",
    links: {
      doc: "https://base-ui.com/react/components/toolbar",
      api: "https://base-ui.com/react/components/toolbar#api-reference",
    },
  },
  {
    slug: ["ui", "tooltip"],
    url: "/docs/ui/tooltip",
    title: "Tooltip",
    description: "A component to display information on hover.",
    links: {
      doc: "https://base-ui.com/react/components/tooltip",
      api: "https://base-ui.com/react/components/tooltip#api-reference",
    },
  },
];

/**
 * Page tree structure for navigation
 * This is generated from the meta.json files
 */
export const pageTree = {
  name: "Documentation",
  children: [
    {
      type: "folder" as const,
      name: "Get Started",
      children: [
        {
          type: "page" as const,
          name: "About Roi UI",
          url: "/docs",
          external: false,
        },
        {
          type: "page" as const,
          name: "Quick Start",
          url: "/docs/start",
          external: false,
        },
        {
          type: "page" as const,
          name: "Components",
          url: "/docs/components",
          external: false,
        },
      ],
    },
    {
      type: "folder" as const,
      name: "UI",
      children: [
        {
          type: "page" as const,
          name: "Accordion",
          url: "/docs/ui/accordion",
          external: false,
        },
        {
          type: "page" as const,
          name: "Alert",
          url: "/docs/ui/alert",
          external: false,
        },
        {
          type: "page" as const,
          name: "Alert Dialog",
          url: "/docs/ui/alert-dialog",
          external: false,
        },
        {
          type: "page" as const,
          name: "Autocomplete",
          url: "/docs/ui/autocomplete",
          external: false,
        },
        {
          type: "page" as const,
          name: "Avatar",
          url: "/docs/ui/avatar",
          external: false,
        },
        {
          type: "page" as const,
          name: "Badge",
          url: "/docs/ui/badge",
          external: false,
        },
        {
          type: "page" as const,
          name: "Button",
          url: "/docs/ui/button",
          external: false,
        },
        {
          type: "page" as const,
          name: "Card",
          url: "/docs/ui/card",
          external: false,
        },
        {
          type: "page" as const,
          name: "Carousel",
          url: "/docs/ui/carousel",
          external: false,
        },
        {
          type: "page" as const,
          name: "Charts",
          url: "/docs/ui/charts",
          external: false,
        },
        {
          type: "page" as const,
          name: "Checkbox",
          url: "/docs/ui/checkbox",
          external: false,
        },
        {
          type: "page" as const,
          name: "Checkbox Group",
          url: "/docs/ui/checkbox-group",
          external: false,
        },
        {
          type: "page" as const,
          name: "Collapsible",
          url: "/docs/ui/collapsible",
          external: false,
        },
        {
          type: "page" as const,
          name: "Combobox",
          url: "/docs/ui/combobox",
          external: false,
        },
        {
          type: "page" as const,
          name: "Command",
          url: "/docs/ui/command",
          external: false,
        },
        {
          type: "page" as const,
          name: "Context Menu",
          url: "/docs/ui/context-menu",
          external: false,
        },
        {
          type: "page" as const,
          name: "Copy Button",
          url: "/docs/ui/copy-button",
          external: false,
        },
        {
          type: "page" as const,
          name: "Dialog",
          url: "/docs/ui/dialog",
          external: false,
        },
        {
          type: "page" as const,
          name: "Dropdown Menu",
          url: "/docs/ui/dropdown-menu",
          external: false,
        },
        {
          type: "page" as const,
          name: "Field",
          url: "/docs/ui/field",
          external: false,
        },
        {
          type: "page" as const,
          name: "Fieldset",
          url: "/docs/ui/fieldset",
          external: false,
        },
        {
          type: "page" as const,
          name: "Form",
          url: "/docs/ui/form",
          external: false,
        },
        {
          type: "page" as const,
          name: "Input",
          url: "/docs/ui/input",
          external: false,
        },
        {
          type: "page" as const,
          name: "Like Button",
          url: "/docs/ui/like-button",
          external: false,
        },
        {
          type: "page" as const,
          name: "Menubar",
          url: "/docs/ui/menubar",
          external: false,
        },
        {
          type: "page" as const,
          name: "Meter",
          url: "/docs/ui/meter",
          external: false,
        },
        {
          type: "page" as const,
          name: "Navigation Menu",
          url: "/docs/ui/navigation-menu",
          external: false,
        },
        {
          type: "page" as const,
          name: "Number Field",
          url: "/docs/ui/number-field",
          external: false,
        },
        {
          type: "page" as const,
          name: "Popover",
          url: "/docs/ui/popover",
          external: false,
        },
        {
          type: "page" as const,
          name: "Preview Card",
          url: "/docs/ui/preview-card",
          external: false,
        },
        {
          type: "page" as const,
          name: "Progress",
          url: "/docs/ui/progress",
          external: false,
        },
        {
          type: "page" as const,
          name: "Radio",
          url: "/docs/ui/radio",
          external: false,
        },
        {
          type: "page" as const,
          name: "Scroll Area",
          url: "/docs/ui/scroll-area",
          external: false,
        },
        {
          type: "page" as const,
          name: "Select",
          url: "/docs/ui/select",
          external: false,
        },
        {
          type: "page" as const,
          name: "Separator",
          url: "/docs/ui/separator",
          external: false,
        },
        {
          type: "page" as const,
          name: "Slider",
          url: "/docs/ui/slider",
          external: false,
        },
        {
          type: "page" as const,
          name: "Switch",
          url: "/docs/ui/switch",
          external: false,
        },
        {
          type: "page" as const,
          name: "Tabs",
          url: "/docs/ui/tabs",
          external: false,
        },
        {
          type: "page" as const,
          name: "Toast",
          url: "/docs/ui/toast",
          external: false,
        },
        {
          type: "page" as const,
          name: "Toggle",
          url: "/docs/ui/toggle",
          external: false,
        },
        {
          type: "page" as const,
          name: "Toggle Group",
          url: "/docs/ui/toggle-group",
          external: false,
        },
        {
          type: "page" as const,
          name: "Toolbar",
          url: "/docs/ui/toolbar",
          external: false,
        },
        {
          type: "page" as const,
          name: "Tooltip",
          url: "/docs/ui/tooltip",
          external: false,
        },
      ],
    },
    {
      type: "folder" as const,
      name: "Blocks",
      children: [
        {
          type: "page" as const,
          name: "AI Chat",
          url: "/docs/blocks/ai-chat",
          external: false,
        },
        {
          type: "page" as const,
          name: "Expandable Card",
          url: "/docs/blocks/card-expandable",
          external: false,
        },
        {
          type: "page" as const,
          name: "Transaction History",
          url: "/docs/blocks/card-history",
          external: false,
        },
        {
          type: "page" as const,
          name: "Image Card",
          url: "/docs/blocks/card-image",
          external: false,
        },
        {
          type: "page" as const,
          name: "Login Card",
          url: "/docs/blocks/card-login",
          external: false,
        },
        {
          type: "page" as const,
          name: "Task Card",
          url: "/docs/blocks/card-task",
          external: false,
        },
        {
          type: "page" as const,
          name: "Website Traffic",
          url: "/docs/blocks/card-traffic",
          external: false,
        },
        {
          type: "page" as const,
          name: "Profile Menu",
          url: "/docs/blocks/profile-menu",
          external: false,
        },
      ],
    },
  ],
};
